// EX07 Using Plugins & Snippet Editor

pipeline {
    agent any

    stages {
        stage('Stage One') {
            steps {
                sh '''
                    echo Stage One
                '''
            }
        }

        stage('Input Stage') {
            steps {
                input message: 'May I go further', ok: 'FURTHER', submitterParameter: 'SUBMITTERNAME'
            
            }
        }

        stage('Stage Two') {
            steps {
                sh '''
                    echo Stage Two
                    
                '''
            }
        }


        }
    }