// EX07 Using Plugins & Snippet Editor

pipeline {
    agent any

    stages {
        stage('Stage One') {
            steps {
                sh '''
                    echo Stage One
                '''
            }
        }

        stage('Veiligheid'){
            input message: 'mag ik doorgaan?', parameters: [choice(choices: ['ja', 'nee'], description: '', name: 'doorgaan')]
        }
        stage('Stage Two') {
            steps {
                sh '''
                    echo Stage Two
                '''
            }
        }


        }
    }