// EX05 Blocks

pipeline {
    agent any

    stages {
        stage('Maandag') {
            steps {
                sh '''
                    echo pfff
                '''
            }
        }

        stage('Dinsdag') {
            steps {
                sh '''
                    echo Pff
                '''
            }
        }

        stage('Woensdag, de week is doormidden') {
            steps {
                sh '''
                    echo hehe
                '''
            }
        }

        stage('Donderdag, bijna weekend') {
            steps {
                sh '''
                    echo Nog even vol houden
                '''
            }
        }

        stage('Vrijdag, echt bijna weekend') {
            steps {
                sh '''
                    echo Npg een paar uurtjes
                '''
            }
        }

        }
    }