// EX05 Blocks

pipeline {
    agent any

    stages {
        stage('Stage Ontwikkel') {
            steps {
                sh '''
                    echo Stage Ontwikkel
                '''
            }
        }

        stage('Stage Test') {
            steps {
                sh '''
                    echo Stage Test
                '''
            }
        }
        stage('Stage Acceptance') {
            steps {
                sh '''
                    echo Stage Acceptance
                '''
            }
        }
            stage('Stage Production') {
            steps {
                sh '''
                    echo Stage Production
                '''
            }
        }
        }
    }