// EX05 Blocks

pipeline {
    agent any

    tools {
        maven 'apache-maven-3.0.1' 
    }

    stages {
        stage('Stage One') {
            steps {
                sh '''
                    echo Stage One
                '''
            }
        }

        stage('Stage Two') {
            steps {
                sh '''
                    echo Stage Two
                '''
            }
        }
        stage('Example') {
            steps {
                sh 'mvn --version'
            }
        }


        }
    }