// EX04 Shell & Variables

pipeline {
    agent any

    stages {
        stage('Stage Klaas') {
            steps {
                sh 'echo My Build Number is: ${BUILD_NUMBER}'
		sh 'echo My BuildTag is: ${BUILD_TAG} '
            }
        }

  

        }
    }
