// EX04 Shell & Variables

pipeline {
    agent any

    stages {
        stage('Stap 1') {
            steps {
                sh 'echo My Build Number is: ${BUILD_NUMBER}'
                sh 'echo My Branch Number is: ${BRANCH_NAME}'
            }
        }

  

        }
    }
