// EX06 Parallel Running

pipeline {
    agent any

    stages {
        stage('Stage One') {
            steps {
                sh '''
                    echo Stage One
                '''
            }
        }

    stage('run-parallel-branches') {
  steps {
    parallel(
      a: {
        echo "This is branch a"
      },
      b: {
        echo "This is branch b"
      }
    )
  }
}

    stages {
        stage('Stage Two') {
            steps {
                sh '''
                    echo Stage Two
                '''
            }
        }

    stage('run-parallel-branches') {
  steps {
    parallel(
      a: {
        echo "This is branch c"
      },
      b: {
        echo "This is branch d"
      }
    )
  }
}


        }
    }



 