// pipeline {
//     agent any

//     stages {
//         stage('Build Stage') {
//             steps {
//                 sh 'echo Not Really Building'
//             }
//         }
//         }
//     }



pipeline {
    agent any 
    stages {
        stage('Example Build') {
            steps {
                sh 'mvn -B clean verify'
            }
        }
    }
}




    // stages {
    //         stage('Build Stage') {
    //             steps {
    //                 sh '''
                           set -x
                           set -e
    //                     mvn test
    //                     mvn install
    //                 '''
    //             }
    //         }
    //         }
    //     }






