pipeline {
    agent any

    stages {
        stage('Build Stage') {
            steps {
                echo 'Fake Building..'
            }
        }
        }
    }



    // stages {
    //         stage('Build Stage') {
    //             steps {
    //                 sh '''
                           set -x
                           set -e
    //                     mvn test
    //                     mvn install
    //                 '''
    //             }
    //         }
    //         }
    //     }






