// EX09 Docker multistage build

pipeline {
    agent any

    stages {
        stage('Stage One') {
            steps {
                sh '''
                    echo Stage One
                '''
            }
        }

        stage('Stage Two') {
            steps {
                sh '''
                    echo Stage Two
                '''
            }
        }


        }
    }

